# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PictureSelect
                                 A QGIS plugin
 This plugin selects pictures
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-24
        copyright            : (C) 2020 by Bruno Vermeulen
        email                : bruno_vermeulen2001@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from pathlib import Path
import os
import sys

# add path to required site-packages not available in QGIS depending on OS
if os.name == "posix":
    import_path = Path(
        "~/.local/share/QGIS/QGIS3/profiles/default/python/site-packages"
    )

elif os.name == "nt":
    import_path = (
        Path(os.getenv("APPDATA")) / "QGIS/QGIS3/profiles/default/python/site-packages"
    )

else:
    import_path = ""

import_path = str(import_path)
if import_path and import_path not in sys.path:
    sys.path.insert(0, import_path)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PictureSelect class from file PictureSelect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .picture_select import PictureSelect

    return PictureSelect(iface)
