# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PictureSelect
                                 A QGIS plugin
 Draws rubberband and displays the pictures within the rectangle
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-14
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Bruno Vermeulen
        email                : bruno.vermeulen@hotmail.com
 ***************************************************************************/
"""
import os

from qgis.PyQt import uic, QtWidgets

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'picture_select_dlg.ui'))

START_YEAR = 2010
END_YEAR = 2026

class PictureSelectDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(PictureSelectDialog, self).__init__(parent)
        self.years_range = range(START_YEAR, END_YEAR + 1)
        self.setupUi(self)
        self.pb_select_all.clicked.connect(self.select_all)
        self.pb_deselect_all.clicked.connect(self.deselect_all)

    def select_all(self):
        for year in self.years_range:
            getattr(self, f'cb_{year}').setChecked(True)

    def deselect_all(self):
        for year in self.years_range:
            getattr(self, f'cb_{year}').setChecked(False)
