# -*- coding: utf-8 -*-
"""
***************************************************************************
 ActiveReceivers
                                 A QGIS plugin
 Shows a rectangle centered on source point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Bruno Vermeulen
        email                : bruno.vermeulen@hotmail.com
 ***************************************************************************/
"""
def classFactory(iface):
    from .active_receivers import ActiveReceivers
    return ActiveReceivers(iface)
