# -*- coding: utf-8 -*-
"""
***************************************************************************
 ActiveReceivers
                                 A QGIS plugin
 Shows a rectangle centered on source point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Bruno Vermeulen
        email                : bruno_vermeulen2001@yahoo.com
 ***************************************************************************/

***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import numpy as np

# if os.name == "posix":
#     import sys

#     import_path = os.path.expanduser(
#         "~/.local/share/QGIS/QGIS4/profiles/default/python/site-packages"
#     )
#     sys.path.insert(0, import_path)

from qgis.PyQt.QtCore import Qt, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QColorConstants
from qgis.PyQt.QtWidgets import QAction

from qgis.core import (
    QgsProject,
    QgsPointXY,
    QgsWkbTypes,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsDistanceArea,
)
from qgis.gui import (
    QgsMapToolEmitPoint,
    QgsRubberBand,
    QgsVertexMarker,
)
from .active_receivers_dialog import ActiveReceiversDialog

AZIMUTH = 0.0  # degrees [0 .. 360]
OFFSET_INLINE = 5000    # meters
OFFSET_CROSSLINE = 2500 # meters
CHECKBOX_CIRCLE = False
CHECKBOX_GEOCENTRIC = False
CIRCLE_STEPS = 50
RAD2DEG = 180.0 / np.pi


class CalcMap:

    def __init__(
        self, canvas, azimuth: float, inline: float, crossline: float, geocentric: bool
    ):
        self.canvas = canvas
        self.azimuth = azimuth * 1 / RAD2DEG
        self.inline_offset = inline
        self.crossline_offset = crossline
        self.geocentric = geocentric
        self.csr_canvas = QgsCoordinateReferenceSystem(
            self.canvas.mapSettings().destinationCrs().authid()
        )
        self.ellipsoid_canvas = self.csr_canvas.ellipsoidAcronym()
        self.diagonal = np.sqrt(
            self.inline_offset * self.inline_offset
            + self.crossline_offset * self.crossline_offset
        )
        csr_wgs84 = QgsCoordinateReferenceSystem("EPSG:4326")
        self.ellipsoid_wgs84 = csr_wgs84.ellipsoidAcronym()
        self.transform_to_wgs84 = QgsCoordinateTransform(
            self.csr_canvas, csr_wgs84, QgsProject.instance().transformContext()
        )
        self.transform_to_canvas = QgsCoordinateTransform(
            csr_wgs84, self.csr_canvas, QgsProject.instance().transformContext()
        )

    def get_bearing(self, corner_type: str, radial: float = 0) -> float:
        match corner_type:
            case "NE":
                bearing = np.arctan2(self.crossline_offset, self.inline_offset)

            case "SE":
                bearing = np.arctan2(self.crossline_offset, -self.inline_offset)

            case "SW":
                bearing = np.arctan2(-self.crossline_offset, -self.inline_offset)

            case "NW":
                bearing = np.arctan2(-self.crossline_offset, self.inline_offset)

            case "CIRCLE":
                bearing = radial - self.azimuth

            case _:
                assert False, f"incorrect option: {corner_type}"

        return bearing + self.azimuth

    def test1(self, point):
        da = QgsDistanceArea()
        da.setEllipsoid(self.ellipsoid_wgs84)

        if self.csr_canvas.isGeographic():
            point_wgs84 = point

        else:
            point_wgs84 = self.transform_to_wgs84.transform(point)

        test_bar = 10_000
        bearing = 0
        result1 = da.measureLineProjected(point_wgs84, test_bar, bearing)

        test_bar = 5_000
        bearing = 90 / RAD2DEG
        result2 = da.measureLineProjected(point_wgs84, test_bar, bearing)

        if self.csr_canvas.isGeographic():
            a = result1[1]
            b = result2[1]

        else:
            a = self.transform_to_canvas.transform(result1[1])
            b = self.transform_to_canvas.transform(result2[1])

        print(f"{a.x()=:.2f}, {a.y()=:.2f}")
        print(f"{b.x()=:.2f}, {b.y()=:.2f}")
        print(f"{point.x()=:.2f}, {point.y()=:.2f}")
        da.setSourceCrs(self.csr_canvas, QgsProject.instance().transformContext())
        da.setEllipsoid(self.ellipsoid_canvas)
        print(f"{da.measureLine(point, a):.1f}")
        print(f"{da.measureLine(point, b):.1f}")

    def test2(
        self, p1: QgsPointXY, p2: QgsPointXY, p3: QgsPointXY, p4: QgsPointXY
    ) -> None:
        da = QgsDistanceArea()
        da.setSourceCrs(self.csr_canvas, QgsProject.instance().transformContext())
        da.setEllipsoid(self.ellipsoid_canvas)
        print(f"{da.measureLine(p1, p2) * 1e-3:.1f}")
        print(f"{da.measureLine(p2, p3) * 1e-3:.1f}")
        print(f"{da.measureLine(p3, p4) * 1e-3:.1f}")
        print(f"{da.measureLine(p4, p1) * 1e-3:.1f}\n")

    def create_point(
        self, point: QgsPointXY, corner_type: str, diagonal: float, radial: float = 0
    ) -> QgsPointXY:
        if self.geocentric or self.csr_canvas.isGeographic():
            da = QgsDistanceArea()
            da.setEllipsoid(self.ellipsoid_wgs84)

            if self.csr_canvas.isGeographic():
                point_wgs84 = point

            else:
                point_wgs84 = self.transform_to_wgs84.transform(point)

            bearing = self.get_bearing(corner_type, radial=radial)
            pointxy = da.measureLineProjected(point_wgs84, diagonal, bearing)[1]

            if self.csr_canvas.isGeographic():
                return pointxy

            else:
                return self.transform_to_canvas.transform(pointxy)

        else:
            # simple cartesian distance - no transformation
            da = QgsDistanceArea()
            da.setSourceCrs(self.csr_canvas, QgsProject.instance().transformContext())
            da.setEllipsoid(self.ellipsoid_canvas)
            bearing = self.get_bearing(corner_type, radial=radial) * RAD2DEG
            pointxy = da.measureLineProjected(point, diagonal, bearing)[1]
            return pointxy

    def add_rectangle(self, point: QgsPointXY) -> tuple[QgsPointXY]:
        """create 4 corner coordinates based on inline and crossline distances"""

        points = ()
        for corner_point in ["NE", "SE", "SW", "NW"]:
            ptxy = self.create_point(point, corner_point, self.diagonal)
            points += (ptxy,)

        return points

    def add_circle(self, point: QgsPointXY) -> tuple[QgsPointXY]:
        radials = np.linspace(0, 2 * np.pi, CIRCLE_STEPS)

        points = ()
        for radial in radials:
            ptxy = self.create_point(point, "CIRCLE", self.inline_offset, radial=radial)
            points += (ptxy,)

        return points


class ActivePatchMapTool(QgsMapToolEmitPoint):
    def __init__(
        self, canvas, azimuth, inline, crossline, checkbox_circle, checkbox_geocentric
    ):
        self.canvas = canvas
        self.checkbox_circle = checkbox_circle
        self.inline = inline
        self.cm = CalcMap(
            self.canvas, azimuth, self.inline, crossline, checkbox_geocentric
        )
        QgsMapToolEmitPoint.__init__(self, self.canvas)
        self.rectangle = None
        self.circle = None
        self.marker = None

    def create_marker(self):
        self.marker = QgsVertexMarker(self.canvas)
        self.marker.setColor(QColorConstants.Red)
        self.marker.setIconSize(3)
        self.marker.setIconType(QgsVertexMarker.ICON_CROSS)
        self.marker.setPenWidth(3)

    def create_rectangle(self):
        self.rectangle = QgsRubberBand(self.canvas)
        self.rectangle.setColor(QColorConstants.Blue)
        self.rectangle.setFillColor(Qt.GlobalColor.transparent)
        self.rectangle.setWidth(2)
        self.rectangle.reset(QgsWkbTypes.PolygonGeometry)

    def reset(self):
        if self.marker:
            self.canvas.scene().removeItem(self.marker)

        if self.rectangle:
            self.canvas.scene().removeItem(self.rectangle)

    def canvasPressEvent(self, e):
        point = self.toMapCoordinates(e.pos())
        point = QgsPointXY(point.x(), point.y())
        self.reset()
        self.create_marker()
        self.show_marker(point)
        self.create_rectangle()
        if self.checkbox_circle:
            self.show_circle(point)

        else:
            self.show_rectangle(point)

    def show_marker(self, point: QgsPointXY):
        self.marker.setCenter(point)

    def show_rectangle(self, point: QgsPointXY):
        p1, p2, p3, p4 = self.cm.add_rectangle(point)
        self.rectangle.addPoint(p1, False)
        self.rectangle.addPoint(p2, False)
        self.rectangle.addPoint(p3, False)
        self.rectangle.addPoint(p4, True)  # true to update canvas
        self.rectangle.show()
        # self.cm.test1(point)
        # self.cm.test2(p1, p2, p3, p4)

    def show_circle(self, point: QgsPointXY):
        points = self.cm.add_circle(point)
        for p in points[:-1]:
            self.rectangle.addPoint(p, False)

        self.rectangle.addPoint(points[-1], True)
        self.rectangle.show()

    def deactivate(self):
        self.reset()


class ActiveReceivers:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        self.actions = []
        self.menu = self.tr("&Active Receivers")
        self.first_start = None
        self.patch = None
        self.azimuth = AZIMUTH
        self.inline_offset = OFFSET_INLINE
        self.crossline_offset = OFFSET_CROSSLINE
        self.checkbox_circle = CHECKBOX_CIRCLE
        self.checkbox_geocentric = CHECKBOX_GEOCENTRIC

    def tr(self, message):
        return QCoreApplication.translate("ActiveReceivers", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        checkable_flag=True,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        action.setCheckable(checkable_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, "resources", "images", "icon.png")
        self.add_action(
            icon_path,
            text=self.tr("Show active receivers"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&Active Receivers"), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        try:
            self.patch.deactivate()

        except AttributeError:
            pass

        result = False
        if self.first_start:
            self.first_start = False
            dlg = ActiveReceiversDialog()
            dlg.lineEdit_azimuth.setText(str(self.azimuth))
            dlg.lineEdit_inline.setText(str(self.inline_offset))
            dlg.lineEdit_crossline.setText(str(self.crossline_offset))
            dlg.checkBox_circle.setChecked(self.checkbox_circle)
            dlg.checkBox_geocentric.setChecked(self.checkbox_geocentric)
            dlg.show()
            result = dlg.exec()

        if result:
            self.azimuth = float(dlg.lineEdit_azimuth.text())
            self.inline_offset = float(dlg.lineEdit_inline.text())
            self.crossline_offset = float(dlg.lineEdit_crossline.text())
            self.checkbox_circle = dlg.checkBox_circle.isChecked()
            self.checkbox_geocentric = dlg.checkBox_geocentric.isChecked()
            dlg.close()

        if self.actions[0].isChecked():
            canvas = self.iface.mapCanvas()
            self.patch = ActivePatchMapTool(
                canvas,
                self.azimuth,
                self.inline_offset,
                self.crossline_offset,
                self.checkbox_circle,
                self.checkbox_geocentric,
            )
            canvas.setMapTool(self.patch)

        else:
            # print("====> exit plugin")
            self.patch.deactivate()
            self.iface.mapCanvas().unsetMapTool(self.patch)
            self.first_start = True
